// constants/provinces.ts

import { Province } from "@/types/assessment";

export const provinces: Province[] = [
  { name: "กระบี่", region: "ใต้", recommendation: "" },
  { name: "กรุงเทพมหานคร", region: "กรุงเทพฯ", recommendation: "มีจำนวนผู้ป่วยไข้เลือดออกสูงสุดเป็นลำดับที่ 2 ของประเทศไทย (พ.ศ.2567)" },
  { name: "กาญจนบุรี", region: "กลาง", recommendation: "" },
  { name: "กาฬสินธุ์", region: "อีสาน", recommendation: "" },
  { name: "กำแพงเพชร", region: "กลาง", recommendation: "" },
  { name: "ขอนแก่น", region: "อีสาน", recommendation: "มีจำนวนผู้ป่วยไข้เลือดออกสูงสุดเป็นลำดับที่ 1 ของภาคอีสาน (พ.ศ.2567)" },
  { name: "จันทบุรี", region: "ตะวันออก", recommendation: "" },
  { name: "ฉะเชิงเทรา", region: "ตะวันออก", recommendation: "" },
  { name: "ชลบุรี", region: "กลาง", recommendation: "มีจำนวนผู้ป่วยไข้เลือดออกสูงสุดเป็นลำดับที่ 1 ของภาคกลาง (พ.ศ.2567)" },
  { name: "ชัยนาท", region: "กลาง", recommendation: "" },
  { name: "ชัยภูมิ", region: "อีสาน", recommendation: "" },
  { name: "ชุมพร", region: "ใต้", recommendation: "" },
  { name: "เชียงราย", region: "เหนือ", recommendation: "มีจำนวนผู้ป่วยไข้เลือดออกสูงสุดเป็นลำดับที่ 1 ของภาคเหนือ (พ.ศ.2567)" },
  { name: "เชียงใหม่", region: "เหนือ", recommendation: "มีจำนวนผู้ป่วยไข้เลือดออกสูงสุดเป็นลำดับที่ 2 ของภาคเหนือ (พ.ศ.2567)" },
  { name: "ตรัง", region: "ใต้", recommendation: "" },
  { name: "ตราด", region: "ตะวันออก", recommendation: "" },
  { name: "ตาก", region: "เหนือ", recommendation: "" },
  { name: "นครนายก", region: "กลาง", recommendation: "" },
  { name: "นครปฐม", region: "กลาง", recommendation: "" },
  { name: "นครพนม", region: "อีสาน", recommendation: "" },
  { name: "นครราชสีมา", region: "อีสาน", recommendation: "มีจำนวนผู้ป่วยไข้เลือดออกสูงสุดเป็นลำดับที่ 2 ของภาคอีสาน (พ.ศ.2567)" },
  { name: "นครศรีธรรมราช", region: "ใต้", recommendation: "มีจำนวนผู้ป่วยไข้เลือดออกสูงสุดเป็นลำดับที่ 1 ของภาคใต้ (พ.ศ.2567)" },
  { name: "นครสวรรค์", region: "กลาง", recommendation: "" },
  { name: "นนทบุรี", region: "กลาง", recommendation: "" },
  { name: "นราธิวาส", region: "ใต้", recommendation: "" },
  { name: "น่าน", region: "เหนือ", recommendation: "" },
  { name: "บึงกาฬ", region: "อีสาน", recommendation: "" },
  { name: "บุรีรัมย์", region: "อีสาน", recommendation: "" },
  { name: "ปทุมธานี", region: "กลาง", recommendation: "" },
  { name: "ประจวบคีรีขันธ์", region: "กลาง", recommendation: "" },
  { name: "ปราจีนบุรี", region: "ตะวันออก", recommendation: "" },
  { name: "ปัตตานี", region: "ใต้", recommendation: "" },
  { name: "พระนครศรีอยุธยา", region: "กลาง", recommendation: "" },
  { name: "พะเยา", region: "เหนือ", recommendation: "" },
  { name: "พังงา", region: "ใต้", recommendation: "" },
  { name: "พัทลุง", region: "ใต้", recommendation: "" },
  { name: "พิจิตร", region: "กลาง", recommendation: "" },
  { name: "พิษณุโลก", region: "กลาง", recommendation: "" },
  { name: "เพชรบุรี", region: "กลาง", recommendation: "" },
  { name: "เพชรบูรณ์", region: "กลาง", recommendation: "" },
  { name: "แพร่", region: "เหนือ", recommendation: "" },
  { name: "ภูเก็ต", region: "ใต้", recommendation: "" },
  { name: "มหาสารคาม", region: "อีสาน", recommendation: "" },
  { name: "มุกดาหาร", region: "อีสาน", recommendation: "" },
  { name: "แม่ฮ่องสอน", region: "เหนือ", recommendation: "" },
  { name: "ยโสธร", region: "อีสาน", recommendation: "" },
  { name: "ยะลา", region: "ใต้", recommendation: "" },
  { name: "ร้อยเอ็ด", region: "อีสาน", recommendation: "" },
  { name: "ระนอง", region: "ใต้", recommendation: "" },
  { name: "ระยอง", region: "ตะวันออก", recommendation: "" },
  { name: "ราชบุรี", region: "กลาง", recommendation: "" },
  { name: "ลพบุรี", region: "กลาง", recommendation: "" },
  { name: "ลำปาง", region: "เหนือ", recommendation: "" },
  { name: "ลำพูน", region: "เหนือ", recommendation: "" },
  { name: "เลย", region: "อีสาน", recommendation: "" },
  { name: "ศรีสะเกษ", region: "อีสาน", recommendation: "" },
  { name: "สกลนคร", region: "อีสาน", recommendation: "" },
  { name: "สงขลา", region: "ใต้", recommendation: "มีจำนวนผู้ป่วยไข้เลือดออกสูงสุดเป็นลำดับที่ 2 ของภาคใต้ (พ.ศ.2567)" },
  { name: "สตูล", region: "ใต้", recommendation: "" },
  { name: "สมุทรปราการ", region: "กลาง", recommendation: "มีจำนวนผู้ป่วยไข้เลือดออกสูงสุดเป็นลำดับที่ 2 ของภาคกลาง (พ.ศ.2567)" },
  { name: "สมุทรสงคราม", region: "กลาง", recommendation: "" },
  { name: "สมุทรสาคร", region: "กลาง", recommendation: "" },
  { name: "สระแก้ว", region: "ตะวันออก", recommendation: "" },
  { name: "สระบุรี", region: "กลาง", recommendation: "" },
  { name: "สิงห์บุรี", region: "กลาง", recommendation: "" },
  { name: "สุโขทัย", region: "กลาง", recommendation: "" },
  { name: "สุพรรณบุรี", region: "กลาง", recommendation: "" },
  { name: "สุราษฎร์ธานี", region: "ใต้", recommendation: "" },
  { name: "สุรินทร์", region: "อีสาน", recommendation: "" },
  { name: "หนองคาย", region: "อีสาน", recommendation: "" },
  { name: "หนองบัวลำภู", region: "อีสาน", recommendation: "" },
  { name: "อ่างทอง", region: "กลาง", recommendation: "" },
  { name: "อำนาจเจริญ", region: "อีสาน", recommendation: "" },
  { name: "อุดรธานี", region: "อีสาน", recommendation: "" },
  { name: "อุตรดิตถ์", region: "เหนือ", recommendation: "" },
  { name: "อุทัยธานี", region: "กลาง", recommendation: "" },
  { name: "อุบลราชธานี", region: "อีสาน", recommendation: "" },
];

// Helper function to get province data
export function getProvinceData(provinceName: string): Province | undefined {
  return provinces.find(p => p.name === provinceName);
}